package com.akun.elibrary.dao;

import com.akun.elibrary.bean.Literatureforborrow;
import com.akun.elibrary.bean.LiteratureforborrowExample;
import com.akun.elibrary.bean.LiteratureforborrowKey;
import java.util.List;

public interface LiteratureforborrowDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int countByExample(LiteratureforborrowExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int deleteByExample(LiteratureforborrowExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int deleteByPrimaryKey(LiteratureforborrowKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	void insert(Literatureforborrow record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	void insertSelective(Literatureforborrow record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	List selectByExample(LiteratureforborrowExample example);
	

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	Literatureforborrow selectByPrimaryKey(LiteratureforborrowKey key);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByExampleSelective(Literatureforborrow record, LiteratureforborrowExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByExample(Literatureforborrow record, LiteratureforborrowExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByPrimaryKeySelective(Literatureforborrow record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table dbo.literatureForBorrow
	 * @ibatorgenerated  Thu Apr 05 15:26:19 CST 2012
	 */
	int updateByPrimaryKey(Literatureforborrow record);
	//===============================================================
	/**
	 * get borrow list<br>
	 * @param key
	 * @param start
	 * @param limit
	 * @return
	 */
	List getBorrowList(String key, int start, int limit);
	/**
	 * get borrow list by book name<br>
	 * @param key
	 * @param start
	 * @param limit
	 * @return
	 */
	List getBorrowListByName(String key, int start, int limit);
	/**
	 * 
	 * get record number<br>
	 * @param key
	 * @return
	 */
	int getBorrowCount(String key);

	/**
	 * get borrow list by group<br>
	 * @param
	 * @return:
	 */
	List<Literatureforborrow> getBorrowListByGroup(String key, int start, int limit);

	/**
	 * get borrow list by category<br>
	 * @param
	 * @return:
	 */
	List<Literatureforborrow> getBorrowListByCategory(String key, int start, int limit);

	/**
	 * get the list about the books that the logged-in student borrowed<br>
	 * @param
	 * @return:
	 */
	List<Literatureforborrow> getBorrowListBySnumber(String theLoginedSnumber, int start, int limit);

	/**
	 * get the list about unreturned books<br>
	 * @param
	 * @return:
	 */
	List<Literatureforborrow> getBorrowListNotReturned(String key, int start, int limit);
	
}